# Generated by Django 3.2.6 on 2022-07-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('view_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sayfa Modeli',
                'verbose_name_plural': 'Sayfa Modelleri',
                'db_table': 'pageModel',
            },
        ),
        migrations.CreateModel(
            name='topMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Üst Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Üst Menü',
                'verbose_name_plural': 'Üst Menüler',
                'db_table': 'topMenuModel',
            },
        ),
        migrations.CreateModel(
            name='bottomMenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=150, null=True)),
                ('userType', models.CharField(blank=True, max_length=100, null=True)),
                ('menuType', models.CharField(blank=True, default='Alt Menü', max_length=100, null=True)),
                ('menuSira', models.SmallIntegerField(default=0)),
                ('topMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottomMenus', to='Admin.topmenumodel')),
            ],
            options={
                'verbose_name': 'Alt Menü',
                'verbose_name_plural': 'Alt Menüler',
                'db_table': 'bottomMenuModel',
            },
        ),
    ]
