# Generated by Django 3.2.6 on 2022-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='denemeColumn',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
