# Generated by Django 3.2.6 on 2022-07-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinedoctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisimmodel',
            name='whoIs',
            field=models.CharField(choices=[('nobody', 'Lütfen kim olduğunuzu belirtiniz'), ('Ben bir psikologum ve sitenize üyeyim', 'Ben bir psikologum ve sitenize üyeyim'), ('Ben bir psikologum ancak sitenize üye değilim', 'Ben bir psikologum ancak sitenize üye değilim'), ('Danışanım/Ziyaretçiyim', 'Danışanım/Ziyaretçiyim'), ('Medya ve İşbirliği', 'Medya ve İşbirliği')], default='None', max_length=150),
        ),
    ]
